# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  env_var:
    import: "package:env_var/builder.dart"
    builder_factories: ["envVarBuilder"]
    build_extensions: {".dart": ["env_var.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
